### ISSUE TITLE
Missing denominator from Equation 2

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/LMA-Matlab#10]
Another discrepancy identified by @HannoSpreeuw:
 
> Equation (6) from L'Heureux is not propagated into the Matlab implementation of equations (42) while this is propagated in the Python code.
> So in the Matlab code we have 
> 
```
dCa=DCa/D0Ca=1
dCO3=DCO3/D0Ca=272.6/131.9
```
> 
> In Python there is an [extra division by 1 − log φ2](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/blob/1c090199ad04910f7f240f82f46924ed8e894b88/marlpde/LHeureux_model.py#L187).

**Comment by EmiliaJarochowska** [comment]
This expression is not actually used in evaluating `dCa` and `dCO3` directly, but it makes diffusion dependent on porosity, which we don't have in the Matlab version. So the gist of this issue is to incorporate it.

**Comment by NiklasHohmann** [comment]
@EmiliaJarochowska tortuosity correction (eq. 6 L'Heureux 2018) is now in the implementation [here](https://github.com/MindTheGap-ERC/LMA-Matlab/blob/3956aed9357e5c30af77adfe139cad0d6f67043b/LMAHeureuxPorosityDiffV2.m#L63). 
Can this issue be closed with this, or are there other corrections to be made?
