### ISSUE TITLE
Match calculation of U with the Python implementation

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/LMA-Matlab#9]
As identified by @HannoSpreeuw:

> Matlab has
> 
`U=(presum + rhorat*Phi^3*(1-exp(10-10/Phi))/(1-Phi))`
> 
> while Python has
> 
```
F = 1 - np.exp(10 - 10 / Phi)
one_minus_Phi = 1 - Phi
U = self.presum + self.rhorat * Phi ** 3 * F /one_minus_Ph
```
> 
> So those two extra brackets in Matlab make a difference: `presum` is also divided by 1-Phi in Matlab.

**Comment by NiklasHohmann** [comment]
Solved by #11
